### ISSUE TITLE
Bring it to the chrome web store

### ISSUE THREAD

**Issue by macx** [timbru31/amazon-tag-remover#1]
Any plans on that?

**Comment by timbru31** [comment]
Hi @macx,

thanks for the request.
I'll try to polish and publish this project by the end of the week 👍

**Comment by timbru31** [comment]
Just a heads up, I've actually noticed that longurl.org is no longer up and running, so I need a new URL expander to check for the amzn.to links.

**Comment by macx** [comment]
Thanks for the update. Is [urlex](http://urlex.org/) a option?

**Comment by timbru31** [comment]
API is sadly premium only, I think bit.ly should work, since amzn.to shortlinks are just enterprise bit.ly versions.
They offer a free API https://dev.bitly.com/links.html

**Comment by timbru31** [comment]
Good news, I've taken a closer look at the requests going to amazon via burp and noticed that after expanding the amzn.to link the normal interception mechanism works fine, so the whole longurl code could be removed: d478d1e1a82807ac7b09648aa649905527dc48e8

**Comment by timbru31** [comment]
Published (should go live soon):
https://chrome.google.com/webstore/detail/amazon-tag-remover/mmajdhfdokfcaiadahjnffhbfjfkmcnc

The addon for Opera is submitted, too, but needs some more time due to manual approval process.

**Comment by macx** [comment]
Thanks a lot for your work, appreciate it. Will test it after launch.

**Comment by timbru31** [comment]
@macx Unfourtanetly Google removed the item again from the store, due to no complying with their "program policies". 👎 

I've asked them what's wrong exactly, hopefully I can (re-)publish it

**Comment by timbru31** [comment]
Google responded to my e-mail and re-enabled the extension again. _Today_ you should be able to test it in your lunch break. Let me know if you find any errors!

**Comment by macx** [comment]
Seems to be working. Thank you very much.
