### ISSUE TITLE
Add support for Amazon Smile

### ISSUE THREAD

**Issue by nico-i** [timbru31/amazon-tag-remover#1087]
Currently only amazon.xyz links are supported, but I order most of my stuff over amazon smile, to donate a portion of amazon's proceeds to charity.

Can you add support for the smile.amazon.xyz domain?

**Comment by timbru31** [comment]
Closing as Amazon Smile will be discontinued :(
(German only https://stadt-bremerhaven.de/amazon-smile-wird-eingestellt/)
