### ISSUE TITLE
Chrome Manifest V3 renders this extension useless. Upgrade to work in new Chrome 127+

### ISSUE THREAD

**Issue by chuckreynolds** [timbru31/amazon-tag-remover#1354]
<img width="725" alt="Screenshot 2024-08-06 at 15 45 53" src="https://github.com/user-attachments/assets/93361086-6827-4b73-be72-73361554d460">
Chrome 127.0.xx update puts notification about Manifest v3 and this extension might now work moving forward. Any plans to update it to be Manifest v3 compliant? 

Some more info about it https://arstechnica.com/gadgets/2024/08/chromes-manifest-v3-and-its-changes-for-ad-blocking-are-coming-real-soon/

**Comment by timbru31** [comment]
Yes, it's planned - I simply had no free time to further look into the Manifest v3 changes.

**Comment by chuckreynolds** [comment]
How we doin Tim? Any updated status? Happy Turkey Day man... not to bother you on it right now but I'm setting up new macbook and the extension is reminding me of this. Cheers

**Comment by timbru31** [comment]
First batch of refactoring was done in https://github.com/timbru31/amazon-tag-remover/commit/61495e06883666689c22a02d2ab6928b1f0d082b

**Comment by timbru31** [comment]
v1.0.0 was uploaded to all four webstores

**Comment by timbru31** [comment]
Chrome, Firefox and Edge are now updated.
Opera is pending a review this usually takes months. Closing as done.
