### ISSUE TITLE
Edge release not available

### ISSUE THREAD

**Issue by Jackymancs4** [timbru31/amazon-tag-remover#222]
Hello @timbru31 
It appears that the Edge release of the extension (for ref: #4 ) has been removed. 

The link in the README (https://www.microsoft.com/store/apps/9NVBVZB6QH92) is unvailable, and the extension does not appear in both [Extensions for Microsoft Edge - Microsoft Store](https://www.microsoft.com/en-us/store/collections/EdgeExtensions/pc/?s=store&skipitems=0) and [Microsoft Edge Insider Addons](https://microsoftedge.microsoft.com/insider-addons/category/EdgeExtensions)

**Comment by timbru31** [comment]
Yeah MS messaged me that it crashed for them and they've disabled the extension. I will investigate what's wrong this weekend on my Windows machine and re-submit it.

**Comment by timbru31** [comment]
Sorry for the delay, this is on my to-do list for this week!

**Comment by timbru31** [comment]
Edge has some quirks, but I've managed to solve them. I'm now in contact with MS to resubmit the extension.

(And of course I'm working towards the new Chromium based store submission)

**Comment by timbru31** [comment]
Legacy Edge update v0.7.2 is awaiting approval.  
Chromium based Edge release v0.8.0 is awaiting approval, too.

**Comment by timbru31** [comment]
Everything approved. Chromium Edge addon is at https://microsoftedge.microsoft.com/addons/detail/mgomlnlopahnglkdhmneklogokbmhden
