### ISSUE TITLE
Support for ascsubtag 

### ISSUE THREAD

**Issue by DocmanCC** [timbru31/amazon-tag-remover#6]
In addition to the tag= parameter, certain affiliates also use an ascsubtag= parameter, ostensibly for more detailed tracking.  I'm not sure if it would still work when it doesn't accompany a tag=, but I assume that since it appears to be a partner derived ID they would be able to link it back to the visitor.  Tracking, regardless. 

See here for some details: https://www.quora.com/How-do-companies-use-ascsubtag-in-Amazon

Use any of the zillions of affiliate links at thewirecutter.com to see this tag in use.

**Comment by timbru31** [comment]
Thanks, haven't spotted an `ascsubtag` parameter yet, but will add it 👍

**Comment by timbru31** [comment]
@DocmanCC released v0.3.0 (Firefox and Opera pending, Chrome should be live within 30-60 mins)
