### ISSUE TITLE
Doesn't remove this referral link

### ISSUE THREAD

**Issue by YesTrustMe** [timbru31/amazon-tag-remover#845]
http://www.amazon.ca/gp/redirect.html?ie=UTF8&location=https%3A%2F%2Fwww.amazon.ca%2Fs%3Fk%3Dv-moda%2Bcrossfade%2B2%26gclid%3DCjwKCAiAp8iMBhAqEiwAJb94z7apTwcSFTlDKzsxOoyJRHwWORcKbqLorUPOuUQRt9vgvdvKGTun8RoC1j4QAvD_BwE%26hvadid%3D212622864711%26hvdev%3Dc%26hvlocphy%3D9001065%26hvnetw%3Dg%26hvqmt%3De%26hvrand%3D6998912440213162803%26hvtargid%3Dkwd-320432548977%26hydadcr%3D1505_9454478%26tag%3Dgoogcana-20%26ref%3Dpd_sl_8mo2fsq8jb_e&tag=redflagdealsc-20&linkCode=ur2&camp=15121&creative=330641

**Comment by timbru31** [comment]
Thanks, will investigate provided link sample
