### ISSUE TITLE
Amazon Order Page keeps autorefreshing constantly

### ISSUE THREAD

**Issue by Aconticello** [timbru31/amazon-tag-remover#948]
I added the tag remover to firefox. When I go to the "ORDER" page on Amazon, it refreshes constantly and it does it so fast that you can't see anything on the order page, just the fact that the browser is trying to do something over and over again. 

I uninstalled the tag remover and it is still doing it. Closed out the browser and reopened - still doing it. Made sure firefox was updated to newest version - still doing it. Reinstalled the tag remover and it is still doing it.

**Comment by timbru31** [comment]
If the extension is not active (aka not installed) there is no way it can cause this loop. This might be a another extension that does this or your browser cache/cookies/LocalStorage are weird.

Can you please: Use a fresh profile, install **only** the extension and then re-try? If it's still occurring, please state the exact URL and FF version and I'm happy to re-open the issue.
